# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: standard_deviation_calculator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='standard_deviation_calculator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n#standard_deviation_calculator.proto\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x01\x32\x44\n\x1bStandardDeviationCalculator\x12%\n\rcalculate_std\x12\x07.Number\x1a\x07.Number\"\x00(\x01\x62\x06proto3'
)




_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Number.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=62,
)

DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), {
  'DESCRIPTOR' : _NUMBER,
  '__module__' : 'standard_deviation_calculator_pb2'
  # @@protoc_insertion_point(class_scope:Number)
  })
_sym_db.RegisterMessage(Number)



_STANDARDDEVIATIONCALCULATOR = _descriptor.ServiceDescriptor(
  name='StandardDeviationCalculator',
  full_name='StandardDeviationCalculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=64,
  serialized_end=132,
  methods=[
  _descriptor.MethodDescriptor(
    name='calculate_std',
    full_name='StandardDeviationCalculator.calculate_std',
    index=0,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_NUMBER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STANDARDDEVIATIONCALCULATOR)

DESCRIPTOR.services_by_name['StandardDeviationCalculator'] = _STANDARDDEVIATIONCALCULATOR

# @@protoc_insertion_point(module_scope)
