# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import get_root_pb2 as get__root__pb2


class RootCalculatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.calculate_root = channel.unary_unary(
        '/RootCalculator/calculate_root',
        request_serializer=get__root__pb2.Number.SerializeToString,
        response_deserializer=get__root__pb2.Number.FromString,
        )


class RootCalculatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def calculate_root(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RootCalculatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'calculate_root': grpc.unary_unary_rpc_method_handler(
          servicer.calculate_root,
          request_deserializer=get__root__pb2.Number.FromString,
          response_serializer=get__root__pb2.Number.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'RootCalculator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
